### ISSUE TITLE
server crash - no such method

### ISSUE THREAD

**Issue by Terpo** [da3dsoul/Additional-Buildcraft-Objects#34] opened 2015-09-29 10:09 UTC
http://pastebin.com/JnXijwXV

Random crash. I joined my server and after a few seconds it crashed. Could not reproduce it and I've no idea in which base it happened.

buildcraft-7.0.25.jar
buildcraft-compat-7.0.12.jar
latest ABO release
Forge #1448 

full modlist: http://blog.terpo.org/upload/mc/modlist.txt

**Comment by da3dsoul** [comment] 2015-09-29 10:20
Meh I wanted to rewrite that anyway, now I have a reason to. You should be able to reproduce it if you use Bonemeal on dirt. There may have been a special case, though.

**Comment by da3dsoul** [comment] 2015-09-29 10:20
And damn! Just when I cleared my issue list. Haha

**Comment by Terpo** [comment] 2015-09-29 10:24
After that you can update to BC7.1 or is it already compatible? _g_

**Comment by da3dsoul** [comment] 2015-09-29 10:27
Dunno, I'm about to update. If it's not compatible, it will be by tomorrow.

**Comment by Terpo** [comment] 2015-09-29 10:31
No need to hurry. LogiPipes and some others need also updates.

**Comment by da3dsoul** [comment] 2015-09-29 10:33
No, it's mainly because I've been playing Minecraft more recently. I have a large pile of updates.

**Comment by asiekierka** [comment] 2015-09-29 15:08
BC 7.1 did remove a few methods deprecated in 7.0 related to pipes, also
you can now define custom PipeTransportRenderers, letting people finally
add custom pipe transports properly.

2015-09-29 12:33 GMT+02:00 da3dsoul notifications@github.com:

**Comment by da3dsoul** [comment] 2015-09-29 16:11
I blame bukkit! _it's still not bukkit's fault_ I'm updating things now. Restealing the gui for emerald pipes as it changed in code (for the ender extraction pipe). Fixing other issues, like the addition of a side in the blockActivated method. Both this issue and the update will be released in a few. I will backport it to BC7.0 as well.

**Closed as completed** 2015-09-29 16:13 UTC
