### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by nister6000** [da3dsoul/Additional-Buildcraft-Objects#10] opened 2015-01-27 20:59 UTC
Hello we got this crash after using "Yellow dye on a stick" on a ground (Chisel)
http://pastebin.com/x4xJZpQp

**Comment by da3dsoul** [comment] 2015-01-30 00:56
Firstly, I was wondering if anyone used/knew about it. Secondly, that is throwing a NoClassDefFoundError...on Minecraft. I'll try something, update and have you let me know, 'cause this is the first I've seen this happen on yellow dye.

**Comment by da3dsoul** [comment] 2015-01-30 01:17
PS, don't touch watermills. They are broken. Not really, but they are very WIP. They do spin, though.

**Comment by nister6000** [comment] 2015-01-30 04:25
http://pastebin.com/AePvhYRH

**Comment by da3dsoul** [comment] 2015-01-30 06:46
Ok...post a full log. http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/mods-discussion/1378862-getting-and-identifying-error-logs

**Comment by da3dsoul** [comment] 2015-01-30 12:18
OK wow I didn't realize how old that thread was. Go to %appdata%.minecraft\logs and pastebin/upload the FML-client-latest.log

**Comment by nister6000** [comment] 2015-01-30 15:17
Full crash: http://pastebin.com/idNxJa90
Full server: http://technist.pl/download/2015-01-29-7.log
Full client: http://technist.pl/download/latest.log

**Comment by da3dsoul** [comment] 2015-01-31 03:09
New pre-release for you. Now try.

**Comment by nister6000** [comment] 2015-01-31 06:57
New crash for you :yum: 
Crash: http://technist.pl/download/crash-2015-01-31_01.50.18-server.txt
Server: http://technist.pl/download/2015-01-31-2.log

**Comment by da3dsoul** [comment] 2015-01-31 07:43
![AAAAAARG](http://img1.wikia.nocookie.net/__cb20141017004832/clubpenguinpookie/images/4/4a/Banging-head-against-the-wall.gif)

is my response.

**Comment by da3dsoul** [comment] 2015-01-31 07:50
It is crashing on this:

``` java
int range = 48;
        try
        {
            range = (int) Math.round(FMLClientHandler.instance().getClient().gameSettings.renderDistanceChunks * 3.5);
        }catch(Exception e) {}
```

It is in a try/catch block. Things that are in try/catch blocks don't crash. They may not work as intended, but they don't crash....

**Comment by da3dsoul** [comment] 2015-02-07 14:57
I'm gonna say it's probably chisel's fault, install openeye and use that. I'll reopen this if it is in fact ABO's fault, but I doubt it.

**Comment by nister6000** [comment] 2015-02-09 22:13
I did not used this with openeye (I will test with this later) but using this on minecraft grass cause the same effect.

**Comment by da3dsoul** [comment] 2015-02-10 01:30
Hmmm....

**Comment by nister6000** [comment] 2015-02-10 01:34
My only idea for this is cauldron incompatibility, but i dont make mods.

**Comment by da3dsoul** [comment] 2015-02-10 01:37
Yes, but that doesn't mean I won't fix it! Explain to me how Cauldron works. I know it is a minecraftforge/bukkit mashup, that's it.

**Comment by nister6000** [comment] 2015-02-10 01:40
That i know is combination of spigot/bukkit/forge, and it also change some stuff.

I will try to find somewhere info about stuff needed for compatibility.

EDIT:
I still did not test this with only forge so we are not sure if cauldron is a problem.

**Comment by da3dsoul** [comment] 2015-02-10 02:02
...Cauldron's github was DCMAed... ugh. just a moment.

**Comment by da3dsoul** [comment] 2015-02-10 02:27
I'm writing two new ways to fix it, let me know if plan B or plan C works. Read the log, you'll know if ctrl+f Additional-Buildcraft-Objects.

**Comment by nister6000** [comment] 2015-02-10 04:26
[23:25:41 WARN]: Couldn't Find Minecraft Class. Maybe using Cauldron/MCPC+?
[23:25:41 WARN]: Well Plan A failed...Plan B!
[23:25:41 WARN]: Plan C?

Yeea it didn't crash.

**Comment by da3dsoul** [comment] 2015-02-10 05:15
The official update will be cleaned up and not log spam. Yay 'bout time it's fixed.

**Closed as completed by da3dsoul** 2015-02-10 05:15 UTC
